services:
  mantasphere:
    image: ghcr.io/finalflick/mantasphere:latest
    build: .
    ports:
      - "8080:80"
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - PLAYTEST_URL=${PLAYTEST_URL:-}
      - PLAYTEST_TOKEN=${PLAYTEST_TOKEN:-}